// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGameplayTags
{
	/** Input Tags **/
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	/** Player Tags **/
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);

	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	
	/** Shared Tags **/
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	PROJECTW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
}
